#!/usr/bin/env python3
"""Build every page of scalita.com from one content file per locale.

The site is still plain static HTML: this writes the HTML, git tracks the
HTML, GitHub Pages serves the HTML. Nothing runs at request time.

Why it exists: five locales times four pages is twenty files that must agree
on the navigation, the footer, the language menu and twenty hreflang links
each. Kept by hand that drifts within a release. Kept here it cannot.

    python3 tool/build.py

Edit tool/content/<locale>.json, never the generated .html.
"""

import json
import os
import re
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "tool", "content")
SITE = "https://scalita.com"

# Order matters: it is the order of the language menu, and English is first
# because it is the default the bare domain serves.
LOCALES = [
    # code, url path, <html lang>, hreflang, og:locale, native name
    ("en", "/",     "en",    "en",    "en_US", "English"),
    ("es", "/es/",  "es",    "es",    "es_ES", "Español"),
    ("fr", "/fr/",  "fr",    "fr",    "fr_FR", "Français"),
    ("pt", "/pt/",  "pt-BR", "pt-BR", "pt_BR", "Português"),
    ("de", "/de/",  "de",    "de",    "de_DE", "Deutsch"),
]

PAGES = ["index", "privacy", "terms", "support"]

BANNER = (
    "<!--\n"
    "  Generated by tool/build.py from tool/content/{code}.json.\n"
    "  Do not edit this file by hand: the next build overwrites it.\n"
    "-->\n"
)

LASTMOD = datetime.date.today().isoformat()


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def page_url(loc_path, page):
    """Absolute URL of one page in one locale."""
    return SITE + loc_path + ("" if page == "index" else page + ".html")


def rel(loc_path, page):
    """The href one locale uses to reach a sibling page of its own set."""
    return "./" if page == "index" else page + ".html"


def asset(loc_path, path):
    """Path to a shared asset from inside a locale directory."""
    return path if loc_path == "/" else "../" + path


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def head_links(loc, page):
    """canonical + the full hreflang set, on every page of every locale."""
    code, loc_path, _, _, _, _ = loc
    out = ['  <link rel="canonical" href="%s">' % page_url(loc_path, page)]
    for c, p, _, hl, _, _ in LOCALES:
        out.append('  <link rel="alternate" hreflang="%s" href="%s">' % (hl, page_url(p, page)))
    out.append('  <link rel="alternate" hreflang="x-default" href="%s">' % page_url("/", page))
    return "\n".join(out)


def lang_menu(loc, page, c):
    """A disclosure menu, not a row of buttons.

    <details> is the only native HTML that opens and closes a panel with no
    script at all: the summary is focusable, Enter and Space toggle it, and
    the links inside leave the tab order when it shuts. The script at the
    bottom of the page only adds Escape and click-outside, which are polish.
    """
    code, loc_path, _, _, _, native = loc
    items = []
    for c2, p2, lang2, hl2, _, native2 in LOCALES:
        current = ' aria-current="true"' if c2 == code else ""
        href = rel(loc_path, page) if c2 == code else p2 + ("" if page == "index" else page + ".html")
        items.append(
            '            <a href="%s" hreflang="%s" lang="%s"%s>%s</a>'
            % (href, hl2, lang2, current, native2)
        )
    return """        <li class="nav-lang">
          <details class="lang-menu">
            <summary aria-label="%s">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">
                <circle cx="12" cy="12" r="9"/>
                <path d="M3 12h18M12 3a15 15 0 010 18M12 3a15 15 0 000 18"/>
              </svg>
              <span>%s</span>
              <svg class="lang-chevron" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
                <polyline points="6 9 12 15 18 9"/>
              </svg>
            </summary>
            <div class="lang-list">
%s
            </div>
          </details>
        </li>""" % (esc(c["nav"]["languageLabel"] % native), esc(native), "\n".join(items))


def nav(loc, page, c):
    code, loc_path, _, _, _, _ = loc
    home = loc_path
    n = c["nav"]
    # On the sub-pages the section anchors have to reach back to that
    # locale's own home page, not the English one.
    anchor = (lambda a: "#" + a) if page == "index" else (lambda a: loc_path + "#" + a)
    return """  <nav>
    <div class="container">
      <a href="%s" class="logo">
        <img src="%s" alt="%s" width="32" height="32">
        Scalita
      </a>
      <button class="menu-toggle" aria-label="%s" aria-expanded="false" aria-controls="nav-menu">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <ul id="nav-menu">
        <li><a href="%s">%s</a></li>
        <li><a href="%s">%s</a></li>
        <li><a href="%s">%s</a></li>
        <li><a href="%s">%s</a></li>
%s
      </ul>
    </div>
  </nav>""" % (
        home, asset(loc_path, "images/logo.svg"), esc(n["logoAlt"]), esc(n["menuLabel"]),
        anchor("features"), esc(n["features"]),
        anchor("pricing"), esc(n["pricing"]),
        anchor("download"), esc(n["download"]),
        rel(loc_path, "support"), esc(n["support"]),
        lang_menu(loc, page, c),
    )


def footer(loc, page, c):
    code, loc_path, _, _, _, _ = loc
    f = c["footer"]
    n = c["nav"]
    anchor = (lambda a: "#" + a) if page == "index" else (lambda a: loc_path + "#" + a)
    return """  <footer>
    <div class="container">
      <div class="footer-content">
        <div class="footer-brand">
          <a href="%s" class="logo">
            <img src="%s" alt="%s" width="28" height="28">
            Scalita
          </a>
          <p>%s</p>
        </div>
        <div class="footer-links">
          <h4>%s</h4>
          <ul>
            <li><a href="%s">%s</a></li>
            <li><a href="%s">%s</a></li>
            <li><a href="%s">%s</a></li>
          </ul>
        </div>
        <div class="footer-links">
          <h4>%s</h4>
          <ul>
            <li><a href="%s">%s</a></li>
            <li><a href="%s">%s</a></li>
          </ul>
        </div>
        <div class="footer-links">
          <h4>%s</h4>
          <ul>
            <li><a href="%s">%s</a></li>
            <li><a href="https://ko-fi.com/pablodm9" target="_blank" rel="noopener">%s</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-bottom">
        <p>&copy; 2026 Pablo Dominguez. %s</p>
        <p>%s</p>
      </div>
    </div>
  </footer>""" % (
        loc_path, asset(loc_path, "images/logo_48.png"), esc(n["logoAlt"]), esc(f["brandLine"]),
        esc(f["productHeading"]),
        anchor("features"), esc(n["features"]),
        anchor("pricing"), esc(n["pricing"]),
        anchor("download"), esc(n["download"]),
        esc(f["legalHeading"]),
        rel(loc_path, "privacy"), esc(c["privacy"]["navLabel"]),
        rel(loc_path, "terms"), esc(c["terms"]["navLabel"]),
        esc(f["supportHeading"]),
        rel(loc_path, "support"), esc(f["supportLink"]),
        esc(f["kofi"]),
        esc(f["rights"]), f["madeBy"],
    )


def small_footer(loc, c):
    """The one-line footer the legal and support pages use."""
    f = c["footer"]
    return """  <footer>
    <div class="container">
      <div class="footer-bottom" style="border-top: none; padding-top: 0;">
        <p>&copy; 2026 Pablo Dominguez. %s</p>
        <p>%s</p>
      </div>
    </div>
  </footer>""" % (esc(f["rights"]), f["madeBy"])


def head(loc, page, c, title, description, extra=""):
    code, loc_path, lang, hl, og, native = loc
    return """<!DOCTYPE html>
<html lang="%s">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>%s</title>
  <meta name="description" content="%s">
%s
  <link rel="icon" type="image/png" sizes="32x32" href="%s">
  <link rel="apple-touch-icon" sizes="192x192" href="%s">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="%s">
%s</head>""" % (
        lang, esc(title), esc(description), head_links(loc, page),
        asset(loc_path, "images/logo_32.png"),
        asset(loc_path, "images/logo_192.png"),
        asset(loc_path, "css/style.css"),
        extra,
    )


# --------------------------------------------------------------------------
# the shared scripts
# --------------------------------------------------------------------------

def scripts(loc, index=False):
    """One script block, no framework, everything optional.

    The page works with JavaScript off: the carousel shows its first slide,
    the language menu opens because <details> opens, and the mobile menu is
    the only thing that needs it.
    """
    code, loc_path, _, _, _, _ = loc
    carousel = ""
    if index:
        carousel = """
      // Screenshot carousel. Stops auto-advancing for anyone who asked their
      // system for less motion; the dots still work.
      var slides = document.querySelectorAll('.screenshot');
      var dots = document.querySelectorAll('.dot');
      var current = 0;

      function show(i) {
        for (var s = 0; s < slides.length; s++) {
          slides[s].classList.toggle('active', s === i);
        }
        for (var d = 0; d < dots.length; d++) {
          dots[d].classList.toggle('active', d === i);
          dots[d].setAttribute('aria-selected', d === i ? 'true' : 'false');
        }
        current = i;
      }

      for (var d = 0; d < dots.length; d++) {
        (function (i) {
          dots[i].addEventListener('click', function () { show(i); });
        })(d);
      }

      var still = window.matchMedia('(prefers-reduced-motion: reduce)');
      if (slides.length > 1 && !still.matches) {
        setInterval(function () { show((current + 1) % slides.length); }, 4500);
      }
"""
    return """  <script>
    document.addEventListener('DOMContentLoaded', function () {
      // Language menu. <details> already opens and closes on its own; this
      // only adds Escape and clicking away, which HTML has no answer for.
      var langMenu = document.querySelector('.lang-menu');
      if (langMenu) {
        document.addEventListener('click', function (e) {
          if (langMenu.open && !langMenu.contains(e.target)) langMenu.open = false;
        });
        langMenu.addEventListener('keydown', function (e) {
          if (e.key === 'Escape' && langMenu.open) {
            langMenu.open = false;
            langMenu.querySelector('summary').focus();
          }
        });
        // Remember a language chosen on purpose, so the redirect on the
        // English page stops sending this visitor back where they came from.
        var links = langMenu.querySelectorAll('a');
        for (var l = 0; l < links.length; l++) {
          links[l].addEventListener('click', function () {
            try { localStorage.setItem('scalita-lang-choice', this.getAttribute('hreflang')); } catch (err) {}
          });
        }
      }

      // Mobile menu.
      var toggle = document.querySelector('.menu-toggle');
      var menu = document.getElementById('nav-menu');
      if (toggle && menu) {
        toggle.addEventListener('click', function () {
          var open = menu.classList.toggle('open');
          toggle.classList.toggle('active', open);
          toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
        });
        var items = menu.querySelectorAll('a');
        for (var i = 0; i < items.length; i++) {
          items[i].addEventListener('click', function () {
            menu.classList.remove('open');
            toggle.classList.remove('active');
            toggle.setAttribute('aria-expanded', 'false');
          });
        }
      }
%s    });
%s  </script>
""" % (carousel, piano_script(loc) if index else "")


def piano_script(loc):
    _, loc_path, _, _, _, _ = loc
    a = asset(loc_path, "audio/")
    return """
    // The C major chord under the piano card.
    var chord = ['60_C4.mp3', '64_E4.mp3', '67_G4.mp3'].map(function (f) {
      var a = new Audio('%s' + f);
      a.load();
      return a;
    });

    function playPianoChord() {
      chord.forEach(function (note, i) {
        note.currentTime = 0;
        setTimeout(function () { note.play(); }, i * 80);
      });
    }
""" % a


def redirect_script():
    """Only the English page carries this: it is the one the bare domain serves."""
    tests = "\n".join(
        "      if (lang.indexOf('%s') === 0) { window.location.replace('%s'); return; }"
        % (c if c != "pt" else "pt", p)
        for c, p, _, _, _, _ in LOCALES if c != "en"
    )
    return """  <script>
    // Send a visitor to their language once, and never again after they have
    // picked one from the menu themselves.
    (function () {
      try { if (localStorage.getItem('scalita-lang-choice')) return; } catch (e) { return; }
      var lang = (navigator.language || navigator.userLanguage || '').toLowerCase();
%s
    })();
  </script>
""" % tests


# --------------------------------------------------------------------------
# index
# --------------------------------------------------------------------------

def icon(name, size=24):
    paths = {
        "range": '<path d="M12 2a3 3 0 00-3 3v6a3 3 0 006 0V5a3 3 0 00-3-3z"/><path d="M5 11a7 7 0 0014 0"/><line x1="12" y1="18" x2="12" y2="22"/>',
        "list": '<line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/>',
        "piano": '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
        "layers": '<polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>',
        "spark": '<path d="M12 2L15.09 8.26L22 9.27L17 14.14L18.18 21.02L12 17.77L5.82 21.02L7 14.14L2 9.27L8.91 8.26L12 2Z"/>',
        "wave": '<polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>',
        "updown": '<line x1="12" y1="3" x2="12" y2="21"/><polyline points="8 6 12 2 16 6"/><polyline points="8 18 12 22 16 18"/>',
        "pencil": '<path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 013 3L7 19l-4 1 1-4L16.5 3.5z"/>',
        "download": '<path d="M12 15V3M12 15L8 11M12 15L16 11M3 17V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V17"/>',
    }
    return ('<svg width="%d" height="%d" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">%s</svg>'
            % (size, size, paths[name]))


def build_index(loc, c):
    code, loc_path, lang, hl, og, native = loc
    i = c["index"]
    sc = asset(loc_path, "images/screenshots/%s/" % code)

    og_alts = "\n".join(
        '  <meta property="og:locale:alternate" content="%s">' % o
        for cc, _, _, _, o, _ in LOCALES if cc != code
    )
    ld = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": "Scalita",
        "operatingSystem": "Android",
        "applicationCategory": "MultimediaApplication",
        "description": i["ogDescription"],
        "inLanguage": [l[3] for l in LOCALES],
        "offers": [
            {"@type": "Offer", "price": "0", "priceCurrency": c["currency"],
             "description": i["pricing"]["free"]["name"]},
            {"@type": "Offer", "price": c["proPriceValue"], "priceCurrency": c["currency"],
             "description": i["pricing"]["pro"]["name"]},
        ],
    }
    extra = """
  <meta name="keywords" content="%s">

  <!-- Open Graph -->
  <meta property="og:title" content="%s">
  <meta property="og:description" content="%s">
  <meta property="og:type" content="website">
  <meta property="og:url" content="%s">
  <meta property="og:image" content="%s/images/og-image-%s.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:locale" content="%s">
%s

  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="%s">
  <meta name="twitter:description" content="%s">
  <meta name="twitter:image" content="%s/images/og-image-%s.png">

  <script type="application/ld+json">
%s
  </script>
""" % (
        esc(i["keywords"]), esc(i["ogTitle"]), esc(i["ogDescription"]),
        page_url(loc_path, "index"), SITE, code, og, og_alts,
        esc(i["ogTitle"]), esc(i["ogDescription"]), SITE, code,
        json.dumps(ld, ensure_ascii=False, indent=2),
    )
    if code == "en":
        extra += redirect_script()

    # --- hero -------------------------------------------------------------
    shots = "\n".join(
        '              <img src="%s%s.jpg" alt="%s" class="screenshot%s"%s width="560" height="1125">'
        % (sc, s["file"], esc(s["alt"]), " active" if n == 0 else "", "" if n == 0 else ' loading="lazy"')
        for n, s in enumerate(i["screens"])
    )
    dots = "\n".join(
        '            <button class="dot%s" role="tab" aria-selected="%s" aria-label="%s"></button>'
        % (" active" if n == 0 else "", "true" if n == 0 else "false", esc(s["alt"]))
        for n, s in enumerate(i["screens"])
    )
    facts = "\n".join('          <li>%s</li>' % esc(f) for f in i["hero"]["facts"])

    hero = """  <section class="hero">
    <div class="container">
      <div class="hero-content">
        <span class="hero-badge">%s</span>
        <h1>%s</h1>
        <p class="hero-lead">%s</p>
        <p class="tagline">%s</p>
        <div class="hero-buttons">
          <a href="#download" class="btn btn-primary">%s %s</a>
          <a href="#new" class="btn btn-secondary">%s</a>
        </div>
        <ul class="hero-facts">
%s
        </ul>
      </div>
      <div class="hero-visual">
        <div class="phone-mockup">
          <div class="phone-screen">
            <div class="screenshot-carousel">
%s
            </div>
          </div>
        </div>
        <div class="carousel-dots" role="tablist" aria-label="%s">
%s
        </div>
      </div>
    </div>
  </section>""" % (
        esc(i["hero"]["badge"]), esc(i["hero"]["title"]), esc(i["hero"]["lead"]),
        esc(i["hero"]["tagline"]), icon("download", 20), esc(i["hero"]["ctaPrimary"]),
        esc(i["hero"]["ctaSecondary"]), facts, shots,
        esc(i["hero"]["carouselLabel"]), dots,
    )

    # --- how it works -----------------------------------------------------
    icons = ["range", "list", "piano"]
    steps = "\n".join(
        """        <li class="step">
          <span class="step-mark"><span class="step-number">%d</span>%s</span>
          <h3>%s</h3>
          <p>%s</p>
        </li>""" % (n + 1, icon(icons[n], 22), esc(s["title"]), esc(s["body"]))
        for n, s in enumerate(i["how"]["steps"])
    )
    how = """  <section class="how" id="how">
    <div class="container">
      <div class="section-header">
        <h2>%s</h2>
        <p>%s</p>
      </div>
      <ol class="steps">
%s
      </ol>
      <div class="piano-strip">
        <button type="button" class="piano-button" onclick="playPianoChord()">%s %s</button>
        <p>%s</p>
      </div>
    </div>
  </section>""" % (esc(i["how"]["title"]), esc(i["how"]["lead"]), steps,
                   icon("piano", 18), esc(i["how"]["pianoLabel"]), esc(i["how"]["pianoNote"]))

    # --- harmony, the one highlight --------------------------------------
    points = "\n".join(
        """          <li>
            <strong>%s</strong>
            <span>%s</span>
          </li>""" % (esc(p["title"]), esc(p["body"]))
        for p in i["harmony"]["points"]
    )
    harmony = """  <section class="spotlight" id="new">
    <div class="container">
      <div class="spotlight-body">
        <span class="badge-new">%s</span>
        <h2>%s</h2>
        <p class="spotlight-lead">%s</p>
        <ul class="spotlight-points">
%s
        </ul>
        <p class="spotlight-note">%s</p>
      </div>
      <div class="spotlight-shot">
        <img src="%sharmony.jpg" alt="%s" loading="lazy" width="560" height="1125">
      </div>
    </div>
  </section>""" % (
        esc(i["harmony"]["badge"]), esc(i["harmony"]["title"]), esc(i["harmony"]["lead"]),
        points, esc(i["harmony"]["note"]), sc, esc(i["harmony"]["alt"]),
    )

    # --- the rest, in four groups ----------------------------------------
    gicons = ["spark", "wave", "updown", "pencil"]
    groups = []
    for n, g in enumerate(i["groups"]):
        tags = "\n".join('            <span class="tag">%s</span>' % esc(t) for t in g["tags"])
        piano = ' clickable" id="piano-card" onclick="playPianoChord()' if g.get("piano") else ""
        hint = '\n          <p class="play-hint">%s</p>' % esc(g["pianoHint"]) if g.get("piano") else ""
        groups.append("""        <div class="group%s">
          <div class="group-icon">%s</div>
          <h3>%s</h3>
          <p>%s</p>
          <div class="content-tags">
%s
          </div>%s
        </div>""" % (piano, icon(gicons[n], 22), esc(g["title"]), esc(g["body"]), tags, hint))

    # the catalog, still behind a disclosure
    scales = "\n".join('              <span class="tag">%s</span>' % esc(s) for s in i["catalog"]["scales"])
    routines = "\n".join(
        '              <li><strong>%s</strong> <span>%s</span></li>' % (esc(r[0]), esc(r[1]))
        for r in i["catalog"]["routines"]
    )
    features = """  <section class="features" id="features">
    <div class="container">
      <div class="section-header">
        <h2>%s</h2>
        <p>%s</p>
      </div>
      <div class="groups">
%s
      </div>

      <details class="catalog-expand">
        <summary>
          <div class="catalog-summary">
            <div class="catalog-summary-icon">%s</div>
            <div>
              <h3>%s</h3>
              <p>%s</p>
            </div>
            <svg class="catalog-chevron" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
              <polyline points="6 9 12 15 18 9"/>
            </svg>
          </div>
        </summary>
        <div class="catalog-details">
          <div class="catalog-column">
            <h4>%s</h4>
            <div class="content-tags">
%s
            </div>
          </div>
          <div class="catalog-column">
            <h4>%s</h4>
            <ul class="routine-grid">
%s
            </ul>
            <p class="catalog-note">%s</p>
          </div>
        </div>
      </details>
    </div>
  </section>""" % (
        esc(i["features"]["title"]), esc(i["features"]["lead"]), "\n".join(groups),
        icon("piano", 22), esc(i["catalog"]["title"]), esc(i["catalog"]["lead"]),
        esc(i["catalog"]["scalesHeading"]), scales,
        esc(i["catalog"]["routinesHeading"]), routines, esc(i["catalog"]["note"]),
    )

    # --- pricing ----------------------------------------------------------
    def plan(p, featured):
        items = "\n".join(
            '            <li><span class="check" aria-hidden="true">&#10003;</span> %s</li>' % it
            for it in p["items"]
        )
        badge = '<span class="pricing-badge">%s</span>\n          ' % esc(p["badge"]) if p.get("badge") else ""
        return """        <div class="pricing-card%s">
          %s<h3>%s</h3>
          <div class="price">%s <span>%s</span></div>
          <ul class="pricing-features">
%s
          </ul>
          <a href="#download" class="btn %s pricing-cta">%s</a>
        </div>""" % (
            " featured" if featured else "", badge, esc(p["name"]), esc(p["price"]), esc(p["period"]),
            items, "btn-primary" if featured else "btn-secondary", esc(p["cta"]),
        )

    pricing = """  <section class="pricing" id="pricing">
    <div class="container">
      <div class="section-header">
        <h2>%s</h2>
        <p>%s</p>
      </div>
      <div class="pricing-cards">
%s
%s
      </div>
      <p class="pricing-note">%s</p>
    </div>
  </section>""" % (
        esc(i["pricing"]["title"]), esc(i["pricing"]["lead"]),
        plan(i["pricing"]["free"], False), plan(i["pricing"]["pro"], True),
        esc(i["pricing"]["note"]),
    )

    # --- download ---------------------------------------------------------
    download = """  <section class="download" id="download">
    <div class="container">
      <h2>%s</h2>
      <p>%s</p>
      <div class="store-buttons">
        <a href="https://play.google.com/store/apps/details?id=com.scalita.app" class="store-button" target="_blank" rel="noopener">
          <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
            <path d="M3.609 1.814L13.792 12 3.609 22.186a.996.996 0 01-.609-.92V2.734a1 1 0 01.609-.92zm10.89 10.893l2.302 2.302-10.937 6.333 8.635-8.635zm3.199-3.199l2.807 1.626a1 1 0 010 1.732l-2.807 1.626L15.206 12l2.492-2.492zM5.864 2.658L16.801 8.99l-2.302 2.303-8.635-8.635z"/>
          </svg>
          <div class="store-text">
            <small>%s</small>
            <strong>Google Play</strong>
          </div>
        </a>
      </div>
      <p class="download-note">%s</p>
    </div>
  </section>""" % (
        esc(i["download"]["title"]), esc(i["download"]["lead"]),
        esc(i["download"]["storeSmall"]), esc(i["download"]["note"]),
    )

    body = "\n\n".join([nav(loc, "index", c), hero, how, harmony, features, pricing, download,
                        footer(loc, "index", c)])
    return "%s%s\n<body>\n%s\n\n%s</body>\n</html>\n" % (
        BANNER.format(code=code), head(loc, "index", c, i["title"], i["description"], extra),
        body, scripts(loc, index=True),
    )


# --------------------------------------------------------------------------
# the text pages
# --------------------------------------------------------------------------

def build_text_page(loc, c, page):
    code, loc_path, _, _, _, _ = loc
    p = c[page]
    wrapper = "legal" if page in ("privacy", "terms") else "support"
    body = p["body"]
    back = '\n        <p class="back-home"><a href="%s">&larr; %s</a></p>' % (
        loc_path, esc(c["footer"]["backHome"]))
    section = """  <section class="%s-page">
    <div class="container">
      <div class="%s-content">
%s%s
      </div>
    </div>
  </section>""" % (wrapper, wrapper, body, back)
    parts = "\n\n".join([nav(loc, page, c), section, small_footer(loc, c)])
    return "%s%s\n<body>\n%s\n\n%s</body>\n</html>\n" % (
        BANNER.format(code=code), head(loc, page, c, p["title"], p["description"]),
        parts, scripts(loc),
    )


# --------------------------------------------------------------------------
# sitemap
# --------------------------------------------------------------------------

def build_sitemap():
    priority = {"index": "1.0", "support": "0.5", "privacy": "0.3", "terms": "0.3"}
    freq = {"index": "weekly", "support": "monthly", "privacy": "monthly", "terms": "monthly"}
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:xhtml="http://www.w3.org/1999/xhtml">']
    for code, loc_path, _, _, _, native in LOCALES:
        out.append("  <!-- %s -->" % native)
        for page in PAGES:
            out.append("  <url>")
            out.append("    <loc>%s</loc>" % page_url(loc_path, page))
            for _, p2, _, hl2, _, _ in LOCALES:
                out.append('    <xhtml:link rel="alternate" hreflang="%s" href="%s"/>'
                           % (hl2, page_url(p2, page)))
            out.append('    <xhtml:link rel="alternate" hreflang="x-default" href="%s"/>'
                       % page_url("/", page))
            out.append("    <lastmod>%s</lastmod>" % LASTMOD)
            out.append("    <changefreq>%s</changefreq>" % freq[page])
            out.append("    <priority>%s</priority>" % priority[page])
            out.append("  </url>")
    out.append("</urlset>")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------

def main():
    written = []
    for loc in LOCALES:
        code, loc_path = loc[0], loc[1]
        with open(os.path.join(CONTENT, code + ".json"), encoding="utf-8") as fh:
            c = json.load(fh)
        outdir = ROOT if loc_path == "/" else os.path.join(ROOT, code)
        os.makedirs(outdir, exist_ok=True)
        for page in PAGES:
            html = build_index(loc, c) if page == "index" else build_text_page(loc, c, page)
            path = os.path.join(outdir, page + ".html")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(html)
            written.append(os.path.relpath(path, ROOT))
    with open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8") as fh:
        fh.write(build_sitemap())
    written.append("sitemap.xml")
    for w in written:
        print("wrote", w)


if __name__ == "__main__":
    main()
